# Generated by Django 5.1.7 on 2025-03-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_useranswer_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
