# Generated by Django 5.1.7 on 2025-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_question_created_at_alter_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='audio_response',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
