# Generated by Django 4.2.20 on 2025-05-06 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0022_delete_userpronunciation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciation_audio', models.FileField(upload_to='pronunciations/', verbose_name='فایل تلفظ')),
                ('is_correct', models.BooleanField(verbose_name='تلفظ صحیح بود؟')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='شماره تلاش')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.vocabularylesson', verbose_name='لغت')),
            ],
            options={
                'verbose_name': 'تلفظ کاربر',
                'verbose_name_plural': 'تلفظ\u200cهای لغت',
            },
        ),
    ]
