# Generated by Django 4.2.20 on 2025-05-06 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0023_delete_listeninganswer'),
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.TextField(verbose_name='پاسخ ۱')),
                ('answer2', models.TextField(verbose_name='پاسخ ۲')),
                ('answer3', models.TextField(verbose_name='پاسخ ۳')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.listeningactivity', verbose_name='تمرین مربوطه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ تمرین شنیداری',
                'verbose_name_plural': 'پاسخ\u200cهای تمرین شنیداری',
            },
        ),
    ]
