# Generated by Django 4.2.20 on 2025-05-06 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_conversationresponse_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Report', '0003_readingsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(blank=True, verbose_name='متن نوشته شده توسط کاربر')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('writing_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.writingtask', verbose_name='تمرین نوشتاری')),
            ],
            options={
                'verbose_name': 'تمرین نوشتاری کاربر',
                'verbose_name_plural': 'تمرین\u200cهای نوشتاری کاربران',
            },
        ),
        migrations.CreateModel(
            name='ConversationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_audio', models.FileField(upload_to='user_conversations/', verbose_name='فایل صوتی کاربر')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.conversationprompt', verbose_name='مکالمه مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ مکالمه معلم',
                'verbose_name_plural': 'پاسخ\u200cهای مکالمه',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=255, verbose_name='پاسخ به سؤال ۱')),
                ('answer2', models.CharField(default='', max_length=255, verbose_name='پاسخ به سؤال ۲')),
                ('answer3', models.CharField(default='', max_length=255, verbose_name='پاسخ به سؤال ۳')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='سؤال مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': ' پاسخ سوالات ',
                'verbose_name_plural': 'پاسخ\u200c سوالات',
            },
        ),
    ]
