# Generated by Django 4.2.20 on 2025-05-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_userwritingtask_conversationresponse_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpronunciation',
            options={'verbose_name': 'تلفظ کاربر', 'verbose_name_plural': 'لغت های کاریر'},
        ),
    ]
