# Generated by Django 4.2.20 on 2025-05-07 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_question_season'),
        ('Report', '0008_readingsubmission_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='season',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.season', verbose_name='درس مرتبط'),
        ),
        migrations.AddField(
            model_name='conversationresponse',
            name='season',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.season', verbose_name='درس مرتبط'),
        ),
        migrations.AddField(
            model_name='userwritingtask',
            name='season',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.season', verbose_name='درس مرتبط'),
        ),
    ]
