# Generated by Django 4.2.20 on 2025-05-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_question_season'),
        ('Report', '0009_answer_season_conversationresponse_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninganswer',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه'),
        ),
        migrations.AddField(
            model_name='readingsubmission',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه'),
        ),
        migrations.AddField(
            model_name='userpronunciation',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه'),
        ),
        migrations.AddField(
            model_name='userwritingtask',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه'),
        ),
    ]
