# Generated by Django 4.2.20 on 2025-05-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_questions_remove_question_questions_and_more'),
        ('Report', '0012_alter_answer_options_remove_answer_answer1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='سؤال مربوطه'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answers',
            field=models.TextField(default='', help_text='تمامی پاسخ\u200cها در یک فیلد به صورت جداگانه وارد میشوند.', verbose_name='پاسخ\u200cها'),
        ),
    ]
