# Generated by Django 4.2.20 on 2025-05-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0015_alter_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
