# Generated by Django 4.2.20 on 2025-05-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_questions_remove_question_questions_and_more'),
        ('Report', '0017_alter_answer_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.question'),
        ),
    ]
