# Generated by Django 4.2.20 on 2025-05-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0018_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeninganswer',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='listeninganswer',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='listeninganswer',
            name='answer3',
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='answers',
            field=models.TextField(default='', help_text='تمامی پاسخ\u200cها در یک فیلد به صورت جداگانه وارد میشوند.', verbose_name='پاسخ\u200cها'),
        ),
    ]
