# Generated by Django 4.2.20 on 2025-05-24 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_alter_grammar_options_alter_grammaraudio_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Report', '0019_remove_listeninganswer_answer1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='پاسخ کاربر')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح است؟')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.grammar', verbose_name='گرامر مربوطه')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.questions', verbose_name='سؤال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ گرامر',
                'verbose_name_plural': 'پاسخ گرامر',
            },
        ),
    ]
