# Generated by Django 4.2.20 on 2025-05-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_bookmark_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
