# Generated by Django 5.1.7 on 2025-03-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_age_group_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'دانشجو'), ('instructor', 'مدرس'), ('admin', 'ادمین')], default='student', max_length=20),
        ),
    ]
