# Generated by Django 5.1.7 on 2025-04-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age_group',
            field=models.CharField(blank=True, choices=[('child', 'کودک'), ('teen', 'نوجوان'), ('adult', 'بزرگسال')], max_length=10, verbose_name='گروه سنی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], max_length=20, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'دانشجو'), ('instructor', 'مدرس'), ('admin', 'ادمین')], default='student', max_length=20, verbose_name='نقش'),
        ),
    ]
