# Generated by Django 4.2.20 on 2025-04-30 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_comment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='لغت')),
                ('image', models.ImageField(upload_to='vocab/images/', verbose_name='تصویر مرتبط')),
                ('translation', models.CharField(max_length=200, verbose_name='ترجمه')),
                ('pronunciation_audio', models.FileField(blank=True, null=True, upload_to='vocab/audio/', verbose_name='فایل صوتی تلفظ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_lessons', to='courses.course', verbose_name='دوره مرتبط')),
            ],
            options={
                'verbose_name': 'درس لغت',
                'verbose_name_plural': 'درس\u200cهای لغت',
            },
        ),
    ]
