# Generated by Django 4.2.20 on 2025-05-01 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_vocabularylesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تمرین')),
                ('audio_file', models.FileField(upload_to='audios/', verbose_name='فایل صوتی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر')),
                ('question1', models.CharField(max_length=500, verbose_name='سوال ۱')),
                ('question2', models.CharField(max_length=500, verbose_name='سوال ۲')),
                ('question3', models.CharField(max_length=500, verbose_name='سوال ۳')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_activities', to='courses.course', verbose_name='دوره مربوطه')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.listeningactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vocabularylesson',
            options={'verbose_name': 'درس لغت', 'verbose_name_plural': 'درس\u200c لغت'},
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
