# Generated by Django 4.2.20 on 2025-05-01 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_listeningactivity_listeninganswer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listeningactivity',
            options={'verbose_name': 'تمرین شنیداری', 'verbose_name_plural': 'تمرین\u200cهای شنیداری'},
        ),
        migrations.AlterModelOptions(
            name='listeninganswer',
            options={'verbose_name': 'پاسخ تمرین شنیداری', 'verbose_name_plural': 'پاسخ\u200cهای تمرین شنیداری'},
        ),
        migrations.AlterField(
            model_name='listeningactivity',
            name='question1',
            field=models.CharField(max_length=500, verbose_name='سؤال ۱'),
        ),
        migrations.AlterField(
            model_name='listeningactivity',
            name='question2',
            field=models.CharField(max_length=500, verbose_name='سؤال ۲'),
        ),
        migrations.AlterField(
            model_name='listeningactivity',
            name='question3',
            field=models.CharField(max_length=500, verbose_name='سؤال ۳'),
        ),
        migrations.AlterField(
            model_name='listeninganswer',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.listeningactivity', verbose_name='تمرین مربوطه'),
        ),
        migrations.AlterField(
            model_name='listeninganswer',
            name='answer1',
            field=models.TextField(verbose_name='پاسخ ۱'),
        ),
        migrations.AlterField(
            model_name='listeninganswer',
            name='answer2',
            field=models.TextField(verbose_name='پاسخ ۲'),
        ),
        migrations.AlterField(
            model_name='listeninganswer',
            name='answer3',
            field=models.TextField(verbose_name='پاسخ ۳'),
        ),
        migrations.AlterField(
            model_name='listeninganswer',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='listeninganswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='ReadingPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(verbose_name='متن روخوانی')),
                ('audio_file', models.FileField(upload_to='reading_audios/', verbose_name='فایل صوتی ضبط\u200cشده')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تمرین روخوانی',
                'verbose_name_plural': 'تمرین\u200cهای روخوانی',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
