# Generated by Django 4.2.20 on 2025-05-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_listeningactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpractice',
            name='admin_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='admin_reading_audios/', verbose_name='فایل صوتی ادمین'),
        ),
    ]
