# Generated by Django 4.2.20 on 2025-05-01 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_listeningactivity_user_vocabularylesson_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='conversation_prompts/', verbose_name='فایل صوتی معلم')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=6, verbose_name='جنسیت صدا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه')),
            ],
            options={
                'verbose_name': 'مکالمه معلم',
                'verbose_name_plural': 'مکالمه\u200cهای معلم',
            },
        ),
        migrations.CreateModel(
            name='ConversationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_audio', models.FileField(upload_to='user_conversations/', verbose_name='فایل صوتی کاربر')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.conversationprompt', verbose_name='مکالمه مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ مکالمه',
                'verbose_name_plural': 'پاسخ\u200cهای مکالمه',
            },
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
