# Generated by Django 4.2.20 on 2025-05-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningactivity',
            name='title',
        ),
        migrations.RemoveField(
            model_name='listeningactivity',
            name='user',
        ),
    ]
