# Generated by Django 4.2.20 on 2025-05-04 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_remove_listeningactivity_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(max_length=500, verbose_name='متن روخوانی')),
                ('admin_audio_file', models.FileField(blank=True, null=True, upload_to='admin_reading_audios/', verbose_name='فایل صوتی ادمین')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه')),
            ],
            options={
                'verbose_name': 'تمرین روخوانی',
                'verbose_name_plural': 'تمرین\u200cهای روخوانی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='reading_audios/', verbose_name='فایل صوتی ضبط\u200cشده')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.readingexercise', verbose_name='تمرین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ارسال تمرین روخوانی',
                'verbose_name_plural': 'ارسال\u200cهای تمرین روخوانی',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='ReadingPractice',
        ),
    ]
