# Generated by Django 4.2.20 on 2025-05-04 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_readingexercise_readingsubmission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'پاسخ تمرین روخوانی', 'verbose_name_plural': 'ارسال\u200cهای تمرین روخوانی'},
        ),
        migrations.RemoveField(
            model_name='writingtask',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='writingtask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='writingtask',
            name='user_text',
        ),
        migrations.CreateModel(
            name='UserWritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(blank=True, verbose_name='متن نوشته شده توسط کاربر')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('writing_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.writingtask', verbose_name='تمرین نوشتاری')),
            ],
            options={
                'verbose_name': 'تمرین نوشتاری کاربر',
                'verbose_name_plural': 'تمرین\u200cهای نوشتاری کاربران',
            },
        ),
    ]
