# Generated by Django 4.2.20 on 2025-05-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_readingsubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': ' پاسخ سوالات ', 'verbose_name_plural': 'پاسخ\u200cهای سوالات'},
        ),
        migrations.AlterModelOptions(
            name='conversationresponse',
            options={'verbose_name': 'پاسخ مکالمه معلم', 'verbose_name_plural': 'پاسخ\u200cهای مکالمه'},
        ),
    ]
