# Generated by Django 4.2.20 on 2025-05-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_answer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': ' پاسخ سوالات ', 'verbose_name_plural': 'پاسخ\u200c سوالات'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer1',
            field=models.CharField(default='', max_length=255, verbose_name='پاسخ به سؤال ۱'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer2',
            field=models.CharField(default='', max_length=255, verbose_name='پاسخ به سؤال ۲'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer3',
            field=models.CharField(default='', max_length=255, verbose_name='پاسخ به سؤال ۳'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question1',
            field=models.CharField(default='سؤال پیش\u200cفرض', max_length=255, verbose_name='سؤال ۱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question2',
            field=models.CharField(default='سؤال پیش\u200cفرض', max_length=255, verbose_name='سؤال ۲'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question3',
            field=models.CharField(default='سؤال پیش\u200cفرض', max_length=255, verbose_name='سؤال ۳'),
            preserve_default=False,
        ),
    ]
