# Generated by Django 4.2.20 on 2025-05-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_vocabularylesson_pronunciation_audio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpronunciation',
            options={'verbose_name': 'تلفظ کاربر', 'verbose_name_plural': 'تلفظ\u200cهای لغت'},
        ),
    ]
