# Generated by Django 4.2.20 on 2025-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_userpronunciation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['order'], 'verbose_name': 'درس', 'verbose_name_plural': 'درس ها'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد درس'),
        ),
    ]
