# Generated by Django 4.2.20 on 2025-05-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_season_options_remove_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='پوستر'),
        ),
    ]
