# Generated by Django 4.2.20 on 2025-05-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingexercise',
            name='supplemental_file',
            field=models.FileField(blank=True, null=True, upload_to='admin_reading_files/', verbose_name='  (عکس یا PDF)'),
        ),
        migrations.AddField(
            model_name='writingtask',
            name='sample_image',
            field=models.ImageField(blank=True, null=True, upload_to='writing_tasks/images/', verbose_name='تصویر '),
        ),
    ]
