# Generated by Django 4.2.20 on 2025-05-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_readingexercise_supplemental_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingexercise',
            name='admin_audio_file',
        ),
        migrations.AlterField(
            model_name='readingexercise',
            name='supplemental_file',
            field=models.FileField(blank=True, null=True, upload_to='admin_reading_files/', verbose_name='(عکس یا PDF)'),
        ),
    ]
