# Generated by Django 4.2.20 on 2025-05-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_readingexercise_admin_audio_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationprompt',
            name='gender',
        ),
        migrations.AlterField(
            model_name='conversationprompt',
            name='audio_file',
            field=models.FileField(upload_to='conversation_prompts/', verbose_name='فایل معلم'),
        ),
    ]
