# Generated by Django 4.2.20 on 2025-05-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_conversationprompt_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPronunciation',
        ),
    ]
