# Generated by Django 4.2.20 on 2025-05-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_delete_userpronunciation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListeningAnswer',
        ),
    ]
