# Generated by Django 4.2.20 on 2025-05-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_delete_listeninganswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingSubmission',
        ),
    ]
