# Generated by Django 4.2.20 on 2025-05-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_delete_readingsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationresponse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='conversationresponse',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='conversationresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userwritingtask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userwritingtask',
            name='writing_task',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='ConversationResponse',
        ),
        migrations.DeleteModel(
            name='UserWritingTask',
        ),
    ]
