# Generated by Django 4.2.20 on 2025-05-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_conversationresponse_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularylesson',
            name='season',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='vocab_lessons', to='courses.season', verbose_name='درس مرتبط'),
        ),
    ]
