# Generated by Django 4.2.20 on 2025-05-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_vocabularylesson_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningactivity',
            name='season',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listening_activities', to='courses.season', verbose_name='درس مرتبط'),
        ),
    ]
