# Generated by Django 4.2.20 on 2025-05-07 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_conversationprompt_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='season',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.season', verbose_name='درس مرتبط'),
        ),
    ]
