# Generated by Django 4.2.20 on 2025-05-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_delete_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningactivity',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/', verbose_name='فایل صوتی'),
        ),
        migrations.AlterField(
            model_name='listeningactivity',
            name='question1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='سؤال ۱'),
        ),
        migrations.AlterField(
            model_name='listeningactivity',
            name='question2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='سؤال ۲'),
        ),
        migrations.AlterField(
            model_name='listeningactivity',
            name='question3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='سؤال ۳'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سؤال ۱'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سؤال ۲'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سؤال ۳'),
        ),
    ]
