# Generated by Django 4.2.20 on 2025-05-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_listeningactivity_audio_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question3',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن سؤال'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.question', verbose_name='سوال مربوطه')),
            ],
        ),
    ]
