# Generated by Django 4.2.20 on 2025-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_remove_question_question1_remove_question_question2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='question1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سؤال ۱'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
