# Generated by Django 4.2.20 on 2025-05-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_image_pdffile_alter_question_question1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه')),
                ('questions', models.ManyToManyField(related_name='question_sets', to='courses.question', verbose_name='سؤالات')),
                ('season', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.season', verbose_name='درس مرتبط')),
            ],
            options={
                'verbose_name': 'مجموعه سوالات',
                'verbose_name_plural': 'مجموعه سوالات',
            },
        ),
    ]
