# Generated by Django 4.2.20 on 2025-05-07 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_questionset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question1',
        ),
        migrations.AddField(
            model_name='question',
            name='questions',
            field=models.TextField(default='', help_text='سوالات را به صورت جداگانه و با فرمت متنی وارد کنید.', verbose_name='سوالات'),
        ),
        migrations.AlterField(
            model_name='question',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.season', verbose_name='درس مربوطه'),
        ),
        migrations.DeleteModel(
            name='QuestionSet',
        ),
    ]
