# Generated by Django 4.2.20 on 2025-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_remove_question_question1_question_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='سوال')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='courses.questions', verbose_name='سوالات'),
        ),
    ]
