# Generated by Django 4.2.20 on 2025-05-08 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_questions_remove_question_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='listening_audios/', verbose_name='فایل صوتی')),
            ],
        ),
        migrations.RemoveField(
            model_name='listeningactivity',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='listeningactivity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listeningactivity',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='listeningactivity',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='listeningactivity',
            name='question3',
        ),
        migrations.AddField(
            model_name='listeningactivity',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='listening_activity_images', to='courses.image', verbose_name='تصاویر'),
        ),
        migrations.AddField(
            model_name='listeningactivity',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='listening_activity_questions', to='courses.questions', verbose_name='سوالات'),
        ),
        migrations.AlterField(
            model_name='listeningactivity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه'),
        ),
        migrations.AlterField(
            model_name='listeningactivity',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.season', verbose_name='درس مرتبط'),
        ),
        migrations.AddField(
            model_name='listeningactivity',
            name='audio_files',
            field=models.ManyToManyField(blank=True, related_name='listening_activities', to='courses.listeningaudio', verbose_name='فایل\u200cهای صوتی'),
        ),
    ]
