# Generated by Django 4.2.20 on 2025-05-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_listeningaudio_remove_listeningactivity_audio_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingexercise',
            name='supplemental_file',
        ),
        migrations.AddField(
            model_name='readingexercise',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='Readin_activity_imagesns', to='courses.image', verbose_name='تصاویر'),
        ),
        migrations.AddField(
            model_name='readingexercise',
            name='pdf_files',
            field=models.ManyToManyField(blank=True, related_name='Readin_activity_questions', to='courses.pdffile', verbose_name='فایل\u200cهای PDF'),
        ),
    ]
