# Generated by Django 4.2.20 on 2025-05-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_remove_readingexercise_supplemental_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingtask',
            name='sample_image',
        ),
        migrations.AddField(
            model_name='writingtask',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='WritingTask', to='courses.image', verbose_name='تصاویر'),
        ),
        migrations.AddField(
            model_name='writingtask',
            name='pdf_files',
            field=models.ManyToManyField(blank=True, related_name='WritingTask_questions', to='courses.pdffile', verbose_name='فایل\u200cهای PDF'),
        ),
    ]
