# Generated by Django 4.2.20 on 2025-05-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_remove_writingtask_sample_image_writingtask_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='grammar/audio/', verbose_name='فایل صوتی')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان فایل صوتی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان گرامر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_files', models.ManyToManyField(blank=True, related_name='grammars', to='courses.grammaraudio', verbose_name='فایل\u200cهای صوتی گرامر')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='دوره مربوطه')),
                ('pdf_files', models.ManyToManyField(blank=True, related_name='grammars', to='courses.pdffile', verbose_name='فایل\u200cهای PDF')),
                ('questions', models.ManyToManyField(blank=True, related_name='grammars', to='courses.questions', verbose_name='سوالات')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.season', verbose_name='درس مربوطه')),
            ],
        ),
    ]
