# Generated by Django 4.2.20 on 2025-05-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_grammaraudio_grammar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='audio_files',
        ),
        migrations.AddField(
            model_name='grammaraudio',
            name='grammar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='courses.grammar', verbose_name='گرامر'),
        ),
    ]
