# Generated by Django 4.2.20 on 2025-05-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_remove_grammar_audio_files_grammaraudio_grammar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammaraudio',
            name='title',
        ),
    ]
