# Generated by Django 4.2.20 on 2025-05-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_remove_grammaraudio_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammaraudio',
            options={'verbose_name': 'گرامر', 'verbose_name_plural': 'گرامر ها'},
        ),
    ]
