# Generated by Django 4.2.20 on 2025-05-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_alter_grammaraudio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammar',
            options={'verbose_name': 'گرامر', 'verbose_name_plural': 'گرامر ها'},
        ),
        migrations.AlterModelOptions(
            name='grammaraudio',
            options={},
        ),
    ]
