# Generated by Django 4.2.20 on 2025-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_alter_grammar_options_alter_grammaraudio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_duration',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='مدت زمان دوره (ساعت)'),
        ),
    ]
