# Generated by Django 4.2.20 on 2025-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_course_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('english', 'انگلیسی'), ('french', 'فرانسوی'), ('german', 'آلمانی'), ('arabic', 'عربی'), ('persian', 'فارسی')], default='persian', max_length=20, verbose_name='زبان دوره'),
        ),
    ]
