# Generated by Django 4.2.20 on 2025-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('انگلیسی', 'english'), ('فرانسوی', 'french'), ('آلمانی', 'german'), ('عربی', 'arabic')], default='persian', max_length=20, verbose_name='زبان دوره'),
        ),
    ]
