# Generated by Django 4.2.20 on 2025-05-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_alter_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('english', 'انگلیسی'), ('french', 'فرانسوی'), ('german', 'آلمانی'), ('arabic', 'عربی')], default='english', max_length=20, verbose_name='زبان دوره'),
        ),
    ]
