# Generated by Django 4.2.20 on 2025-05-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_alter_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_status',
            field=models.CharField(choices=[('yes', 'دارد'), ('no', 'ندارد'), ('pending', 'در حال بررسی')], default='yes', max_length=10, verbose_name='وضعیت مدرک'),
        ),
    ]
