# Generated by Django 4.2.20 on 2025-06-01 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0053_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='content',
            field=models.TextField(blank=True, verbose_name='محتوای درس'),
        ),
        migrations.AddField(
            model_name='season',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='درس رایگان'),
        ),
        migrations.AddField(
            model_name='season',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک ویدیو'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.season', verbose_name='درس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیشرفت کاربر',
                'verbose_name_plural': 'پیشرفت کاربران',
                'unique_together': {('user', 'season')},
            },
        ),
    ]
