# Generated by Django 4.2.17 on 2025-06-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_season_content_season_is_free_season_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='content',
        ),
        migrations.RemoveField(
            model_name='season',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='season',
            name='video_url',
        ),
    ]
